---
#
# Ansible managed
#
repository:
  description: Install and configure postfix on your system.
  homepage: https://buluma.co.ke/
  topics: installer, mailserver, package, postfix, security, system, ansible, molecule, tox, playbook, hacktoberfest
