---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if port 25 is open
      ansible.builtin.wait_for:
        port: 25

    - name: Check if a mail can be sent
      community.general.mail:
        from: "Michael Buluma <michael@example.com>"
        to: "Michael Buluma <root@example.com>"
        subject: Testing buluma.postfix.
        body: Testing the ansible role postfix.
