---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if port 25 is open
      ansible.builtin.wait_for:
        port: 25

    - name: Check if postfix service is running
      ansible.builtin.service_facts:

    - name: Assert postfix is active
      ansible.builtin.assert:
        that:
          - "'postfix' in services"
          - "services['postfix']['state'] == 'running'"
        quiet: true
